language: csharp
solution: Knapsack.sln
sudo: false
install:
  - nuget restore Knapsack.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Knapsack.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./Knapsack.Tests/bin/Release/Knapsack.Tests.dll